### PR TITLE
Prevents Notification from being sent on first login - Fixes #17

### LINKED ISSUE #17: Avoid/Prevent login alert from being sent upon registration
The package automatically sends an alert for new device login as soon as the user completes registration (even before the verification email is sent) which causes unnecessary confusion for the user. 

The aim of this issue is to prevent the very first/initial "new device" alert from being sent and add that device into the record as a "safe" one.

### PR DESCRIPTION
**Pull request by TechTailor**
This minor change prevents notification from being sent when the user is logging in for the first time (since it doesn't really make sense to notify the user of a "new device" login), also prevents confusion among user who receive the alert even before they receive the email verification link.

### CODE REVIEW

**Comment by TechTailor** [comment]
@yakidahan can you review & merge this?

**Comment by TechTailor** [comment]
Sorry my bad, accidentally commited here.

**Comment by kb6673** [comment]
@yakidahan Any plans to merge this?

**Comment by TechTailor** [comment]
Considering there's been no response from the maintainer in almost 9 months, I don't think they intend on merging this. However, a simple response with yes or no would have been better.

Ended up creating my own package (borrowing some from this one) along with some other features I needed for my projects.

-TT

**Comment by kb6673** [comment]
@TechTailor Is this your fork? https://github.com/Spargon/Laravel-Auth-Logger

**Comment by TechTailor** [comment]
> @TechTailor Is this your fork? https://github.com/Spargon/Laravel-Auth-Logger

Yes. It also uses an additional package to parse user-agent data and will be adding some additional features (which I personally use in my other projects.

**Comment by yakidahan** [comment]
Hi @TechTailor,

First of all, thank you for your support of this package.

I apologize for not responding to this PR so far, the last few months have been a bit busy for me...

I think it's a little wrong to do it that way, because after clearing old logs, there will be a situation where there will no longer be a login log and this way the user will not receive an alert on (suspicious) login from a new device, so I would rather receive an alert (unnecessary) when registering, than not receive an important alert in the future.

If you have an idea how to deal with this situation I would love to know.

**Comment by TechTailor** [comment]
Hey @yakidahan,

Thanks for responding. I realized you must have been busy that's why I ended up creating my own version (needed user-agent parser integration as allot of my projects needed them and I wanted a single integration for it).

This may not be the most ideal way of implementing it, but I guess it came from my own use-case, where I usually hold/store logs for a very long time (6-9 months) and in most of them the user accounts are disabled and require reactivation if they don't login for 90 days straight. So for me, this way doesn't present a problem. 

The only way when this becomes an issue is when a user hasn't logged in for a very long time (longer than the log:clear period). say a user didn't login for 100 days straight and u ended up clearing logs old than 90 days, in that case, they won't receive an alert. but then again I personally think its a good/better practice to require some sort of re-activation/verification if the user is inactive for a long time.

Lastly, it's not about sending an unnecessary alert, its about user experience - when a user registers an account, if they receive a suspicious login alert before they even receive the verification email, imho it just shows a poor system design. Offcourse you can avoid that by not auto-logging upon registration, but if the user logs in again without checking/verifying email, he will still get login alert which is not something I like to see.

I will look into any other ways of doing this - I guess from the top of my head, one simple way would be for clear command to check and ignore deletion if its the only entry of that user in db. This way, the db always maintains at least one-record of a user regardless of how old it is and will always send alert.

-TT

**Comment by TechTailor** [comment]
Well, this works/flows better.

**Comment by yakidahan** [comment]
So I merge this PR with this solution:
Checking user creation time compared to login time and if it is less than a minute (from tests I did there is a few seconds difference so I did a minute) don't send an alert.

**Comment by TechTailor** [comment]
Yeah, this is good and should cover most if not all use-cases. There might be some rare edge-cases (specific to my implementations) but I will find a workaround for that.

**Pull request merged**
